apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-client-nooz
    service: web-client-nooz
  name: web-client-nooz
  namespace: web-client
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: web-client-nooz
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: link-iterable-nooz
  namespace: web-client
spec:
  ports:
    - port: 43
  type: ExternalName
  externalName: links.iterable.com
