apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-admin
  namespace: web-admin
  labels:
    app: web-admin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-admin
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70