apiVersion: v1
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1id7aFZgpGs+a2JjT9Xrg+Hcm5A=,iv:n7uKmfIT+8JMNz6lyB6607q5YSbN4pYVvs/F4DvcFbs=,tag:GXoajYF5r6RaKKPlVdaD9Q==,type:str]
    BUCKET_NAME: ENC[AES256_GCM,data:/2aU5wGgXDno92H0EJFFbE9Row==,iv:W7CQ+fVHRxranwKlyzrTKvWyyNW5wHVx4H0mNpLKdz8=,tag:Lx6qQ4SVR6t22sQu6z/DqA==,type:str]
    ENDPOINT_URL: ENC[AES256_GCM,data:Pt++0pX4T6Kuc1HnZ2Xz7TKlqcGqSZ1isJRnqwe6BVu33g==,iv:woygVnSbNYOY0APJdWxNvi5ds1dEC0rtWITgzfJZzmQ=,tag:3X/TULecjKOS526qDpK7ww==,type:str]
    REGION: ENC[AES256_GCM,data:/G+RkJ/DCfni,iv:BjsoVSFbP6wkIMWDkMIorXGXnskArLQ/hjH2+K86kPs=,tag:mbosCB+Nxuvl64wSnH06yw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wbzGi9I8OjE9KpT37wPU+MxkzQXnQDRr5knEc+wp1GEaeM9lBqLKPg==,iv:ZgQZCBcIgdtSVHkyNlfJRw/uYnBpIE4ZKp43j+Nublg=,tag:vwfHbQ9AKbqDqwVdqtLxiA==,type:str]
kind: Secret
metadata:
    name: s3
    namespace: erpnext
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-09-15T15:59:32Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wE4jrJ3sdhiZ6YQUcI886QWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+bG4WVFMA8mWZtNKAgEQgDuTxXNUK3l5pmb7Xy+TGnO7ngo9Wjt5KoIvFhoioYmLUUx2AR5QN2yqWd8U51AK4qvWQmoEBJsYDQTKAw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-27T23:21:38Z"
    mac: ENC[AES256_GCM,data:ZZhvziNIUWjbSQUDZO1rOADFLA0CKtMl5m7VUvQNuODzRJJDz42YDNMZaNj+yCXNjIzhQZih6AtAwTURrtwnP8ueJWi0bWwoorsc7iIzCX8FojI0O4cZ+IvXURVFMF0uEDceK4pL2DKsMxv9ExMM7Ycj74rwAajygSxDA8TvKqE=,iv:TqV8Dvv94Achm/p9pIjEuFwabeL2qbzuMJ/xbElKAr0=,tag:ff0Vrn7EoJy4PNsa0Ey2PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
