# Default values for calert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configmap:
    # All timeouts and durations are in milliseconds.
  server:
    address: ":6000"
    socket: "/tmp/calert.sock"
    name: "calert"
    # WARNING If these timeouts are less than 1s, the server connection breaks.
    read_timeout: "8000"
    write_timeout: "8000"
    keepalive_timeout: "300000"
  app:
    template_file: "/etc/calert/message.tmpl"
    max_size: 4000
    http_client:
      max_idle_conns: "100"
      request_timeout: "8000"
      proxy_url: "http://internal-squid-proxy.com:3128"
  rooms: |

    [app.chat.monitoring]
    notification_url = "https://chat.googleapis.com/v1/spaces/AAAArT6GoDI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=AGCH2x2geISCDSThXlg6k7qi70BsVE-QArgaq5qCQuM%3D"

template_file: |
  *{{ .Labels.alertname | Title }} - {{.Status | Title }} ({{.Labels.severity | toUpper }})*
  {{ range .Annotations.SortedPairs -}}
  {{ .Name }}: {{ .Value}}
  {{ end -}}

replicaCount: 1

command:
- "./calert"
- "--config.file=/etc/calert/config.toml"

nodeSelector:
  purpose: tools
