apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/server-snippet: |
    #  proxy_hide_header Access-Control-Allow-Origin;
    #  add_header Access-Control-Allow-Origin "*" always;
  name: client-api-luuna
  namespace: client-api
spec:
  rules:
    - host: client-api.luuna.mx
      http:
        paths:
          - backend:
              service:
                name: client-api-luuna
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
