namespace: client

generators:
  - secret-generator.yaml

resources:
  - ../../../base/web
  - ingresses

configMapGenerator:
  - name: client-api-luuna
    namespace: client-api
    literals:
      - DEBUG="False"
      - BRAND=LUUNA
  - name: client-api-nooz
    namespace: client-api
    literals:
      - DEBUG="False"
      - BRAND=NOOZ

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: client-api-luuna
      namespace: client-api
    spec:
      template:
        spec:
          containers:
            - name: api
              image: luuna/client-api:master-2a0c7fa702fd81722d5a37fbe28f7ceb84c5cdb5
              command:
                - /code/Docker/entrypoint-production.sh
              envFrom:
                - configMapRef:
                    name: client-api
                - configMapRef:
                    name: client-api-luuna
                - secretRef:
                    name: client-api
                - secretRef:
                    name: client-api-luuna
  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: client-api-luuna
      namespace: client-api
    spec:
      minReplicas: 2
      maxReplicas: 20
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: client-api-nooz
      namespace: client-api
    spec:
      template:
        spec:
          containers:
            - name: api
              image: luuna/client-api:master-2a0c7fa702fd81722d5a37fbe28f7ceb84c5cdb5
              command:
                - /code/Docker/entrypoint-production.sh
              envFrom:
                - configMapRef:
                    name: client-api
                - configMapRef:
                    name: client-api-nooz
                - secretRef:
                    name: client-api
                - secretRef:
                    name: client-api-nooz
  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: client-api-nooz
      namespace: client-api
    spec:
      minReplicas: 1
      maxReplicas: 1
