apiVersion: v1
kind: Secret
metadata:
  name: erpnext-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-10.3.3
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "Y2hhbmdlaXQ="
  mariadb-password: "Y2hhbmdlaXQ="