apiVersion: v1
kind: ServiceAccount
metadata:
  name: erpnext-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-10.3.3
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: false