apiVersion: v1
stringData:
    PAYPAL_SECRET: ENC[AES256_GCM,data:6OjorOHev7XtI5mZ18FS+L0aB3QkpQlY8zeeTS0qqXldZjXKdU/NgOV8pEo/DogKBNGD7OxGqRrMkJ8Jlv4cNNZmraJxwZZ0U1AUYXktc4M=,iv:EL/768Qz/cjnWldtE38L+xMHGoeWaJFGsjRYfjLomRk=,tag:ZTLTL9CwN+6dV6UI23FgLw==,type:str]
    PAYPAL_CLIENT_ID: ENC[AES256_GCM,data:qSqCIf/7ZQmI44LFRrCQ5VmRTUiyU5/23U6nWWtFoOSLuMPBownblJTR/3X1SNTZq+K7hun0Qg7uFJfqHIqoUr9YufflGVIjQOlIVMCR08E=,iv:5QpskVus6U/AohtkdrboEupci4WRKqDyx0h5JR619BE=,tag:79/mZSNlNDz2EeXGton5BQ==,type:str]
    PAYPAL_MERCHANT_ID: ENC[AES256_GCM,data:jKi6aw214yXSis2dpQ==,iv:RpCjQGiu6qFxcX3r65pkeDFwNr+94vgDADW1HHFpe0c=,tag:QPDZRtKjcssXbuQH3vJCKA==,type:str]
    ALBA_BROKER_URL: ENC[AES256_GCM,data:ztwBQdxMzf9rOAoCtfES8KzLgnNq+JVHeVP3X1mX7B48XRk0Yg+IzJ+wyXwaaJmMIQy43ApzCTaOd9MPqMQ11KJg/tfeZBpsxT3Riimxf5LJMWs=,iv:fi2vuSTIHZPJTHGMeFvaUaqhRN4UeTbthYq1b866SUo=,tag:4HY0hlXiOX749A7/Bf/sfg==,type:str]
    ATRATO_KEY: ENC[AES256_GCM,data:l8IhHV1wfNEOPN7u9dY=,iv:Fz6TJy23K7AWVig7XsP4BotutDy/Ro73oHaTs6GCdA8=,tag:zrP/btCz/PZsbRnXhQkX2g==,type:str]
    ATRATO_USER: ENC[AES256_GCM,data:HjJYSzE=,iv:zBfRX+BES7KX5wSQo+fjFcJQZdQvp6bFkV1MPWBKTwM=,tag:IXtPnhFelJ3xhNiZqD05Iw==,type:str]
    ATRATO_PARTNER_USER: ENC[AES256_GCM,data:WuROIhY=,iv:aPjbiacMQaaYC5H5txNjbI0MdpARgrjRsN0Bz5KmIq0=,tag:7trcjXNCJaTSR6SoEtxELQ==,type:str]
    ATRATO_PARTNER_PASSWORD: ENC[AES256_GCM,data:Z81zzBA3lCpUtQ==,iv:WvSfr7jOWSBx23kPfaO7S5KZUrvH5gmSJGgr/XMjhWc=,tag:gp4w8fXV1AL8mzhzc0iOPA==,type:str]
kind: Secret
metadata:
    name: client-api-luuna
    namespace: client-api
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-04T05:33:57Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wEii4Ew2+ws0tRjc7KIQnUwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkUj/drdOLMd7bpaLAgEQgDs+qlv4m5cEjiEjVG71DsRsYBKwTXLCogpXClYiRRs0nKngntaXZuZbgQbhrWnM/OEJU/wEsAvNVP83vg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-26T02:08:19Z"
    mac: ENC[AES256_GCM,data:udctAzVBxrICJxb6YH2QIkv9bQ6Ee/JgBv4zFaoDlA0lJcD93f2fbKRz5quyjoSvMPE+XA7cXn7gltVZf8abo8VXVsQSQc90dkQIUn0kO2dWzDpeWj1anx5gmp0+15/X2kdgkLIss9pZB2vY0BS4rkHFGwLw5SMH+Lx5/ycRyK0=,iv:PAvWhaGdcaYrYAc4tSkTl+YXacDM33K7n8whv0oWrXg=,tag:7pHkeFxhgv5g7x4UMarq5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
