apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: erpnext-redis-queue
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis-queue
    helm.sh/chart: redis-queue-16.4.0
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/managed-by: Helm