apiVersion: v1
kind: Service
metadata:
  name: erpnext-redis-queue-master
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis-queue
    helm.sh/chart: redis-queue-16.4.0
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
      nodePort: null
  selector:
    app.kubernetes.io/name: redis-queue
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/component: master