apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-client-nooz
  name: web-client-nooz
  namespace: web-client
spec:
  selector:
    matchLabels:
      app: web-client-nooz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-client-nooz
    spec:
      automountServiceAccountToken: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: sitemap
          configMap:
            name: nooz-sitemap
        - name: nginx-var-cache
          emptyDir: {}
        - name: nginx-var-run
          emptyDir: {}
      containers:
        - name: web-client
          image: luuna/web-client:luuna-5f719913033474bdb7e85bc16297ed53dbd4a6b7
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /_health
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 8
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 10000
            runAsUser: 10000
        - name: nginx
          image: nginx:1.20-alpine
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: sitemap
              mountPath: /statics/
            - name: nginx-var-cache
              mountPath: /var/cache/nginx
            - name: nginx-var-run
              mountPath: /var/run/
          readinessProbe:
            httpGet:
              path: /_health
              port: 8000
              scheme: HTTP
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 7
          resources:
            requests:
              memory: "500Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 10000
            runAsUser: 10000
      enableServiceLinks: true
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        purpose: frontend
      restartPolicy: Always
      serviceAccount: web-client
      serviceAccountName: web-client
