apiVersion: v1
stringData:
    AMQP_QUEUE_BROKER: ENC[AES256_GCM,data:cwWM6VraKsV4JFw6gq7gQnw4P6vs/yRX7O3RiKJmSERnKE2rYIcpXcid9IUHjX2UUuge8YBKQGpJHE9ZeETSUA/srpt6MUyHZoz7hPVdDWb3HYFeqbtuzVMsQQ==,iv:I/2ajDJSXhf7lOwlOzSMOeZnEpCO8pvoAaU6CTR6Eek=,tag:AaqA0332Br8srcklW0ouKw==,type:str]
    AMPQ_RESULT_BACKEND: ENC[AES256_GCM,data:6NTRC6zFiJCQ4a1776bM4vgbIlZ3rVN0dtNHT3OIptjfg4q0ei0o/4uj8C895ut+MYzGA4VSD90r10VSBlMwLxHgTxCoBMUib+HZJQsWuCNOUR8GMJgXn1Hlf2qUtLLWcic=,iv:Nbh5pyKuV+6NIKV+b3lwXNfaMfMbMGT8wKWmFDkpy/I=,tag:cKFjSGOjJps1jJH010VIdw==,type:str]
    AMPQ_QUEUE: ENC[AES256_GCM,data:d0FBUkK6Tp/Lcg==,iv:AbnP7bN+QMY+yTunYldkN7LWUf3VsctCTCj/OVed5pI=,tag:HsUeppR2yqANmVV5XYjvRw==,type:str]
    MONGODB_URL: ENC[AES256_GCM,data:idH812x+LD9BFWFA+bHmCIQLktdbacJTHJNTUTaU/5+a6ZJjwKiBHjS9Po+uzc6o4yHNabgaMw/a37IqjrG+nUW44OaXVWEkgITUW0E1gtrlYD1RPdKVHv4jcM/9ZSI1PGrncoR77MyiZDjMrThqxrB1lQqLXFVu,iv:5WN4vD1opWqWUAde+TPJRmFX7Bw6s6q6PepX0IziHoo=,tag:YmpxAFeFHUDZYNDkDkdc4w==,type:str]
    ZECORE_BASE_URL: ENC[AES256_GCM,data:vUBPTBSar5fUmbIFWTKM406+v55l5S+Wx0A=,iv:py6KIucza3QqYNpOiUlt+fCazb8yKyZdNV1Q8P0jsgE=,tag:WyBQz7HvH5ELKfBxLj3KWQ==,type:str]
    ZECORE_API: ENC[AES256_GCM,data:DgX2GcAO50kAFTAYz3Rjs+u3pU4CJ5PTrXu3UNPM,iv:gVJ7ITqC/WCQNlw+XhWAAdY2a0VpBzPGwbW8Eqsy8Go=,tag:t1NruvJl5tOh9WmMIY+6qQ==,type:str]
    ZECORE_TOKEN: ENC[AES256_GCM,data:1vdSZ4/p0evqqTIQP8D9TFgYdfbHAbsGWV86GiTmRA==,iv:qRszmWOucIOmX2w6ZBnJldH5Q6gf7IOFxNQ1zXvfHBg=,tag:9uSefXuItnrGcWgQuMlavQ==,type:str]
    INVENTORY_CACHE_SECONDS: ENC[AES256_GCM,data:vX86,iv:TjFn7ZO0Mn0B6ICIkKAfDpE0l/WWTfo5RfIQBJVOOhU=,tag:bnAI22whqq9A/0GMM6Q/aQ==,type:str]
    ALGOLIA_APPLICATION_ID: ""
    ALGOLIA_API_KEY: ""
    ALGOLIA_CATEGORIES: ""
    ZECORE_API_WAIT_MS: ENC[AES256_GCM,data:ArR+4w==,iv:8pGSZ3qRhXsixizaqMLZM495aOzs1GXtCm38Ri3fbhE=,tag:ijhuqnXsfZRdhWWPgQGohA==,type:str]
    CATALOG_AUTH_TOKEN: ENC[AES256_GCM,data:2q8G7tExknEmlyLYvT1Yeh1t/Cc/Yc6KavntL4BCHQE=,iv:OWL3a9U+hvG02te7zRLT2W8lsbzV+uZb9abMO+Z5hW0=,tag:jIDrIOfP2Rs7N+0QSbhM+w==,type:str]
    VALID_VOUCHER_PREFIX: ENC[AES256_GCM,data:h+p1SoZXRc/H/egSB3r8,iv:ogISQ26N8xxUBc9meu56nOdHOZOI4fRKsQuoWSYO008=,tag:2S10uBv0de3nmd8pgL0ADg==,type:str]
    WORKER_PORT: ENC[AES256_GCM,data:VAsoQQ==,iv:Ph9Eqfzf42rfaimQSUtgwmi9tdgmgXVBfxK+9u/+sZo=,tag:ZKCKStEWzgDZddSOwJn25Q==,type:str]
    LOYALTY_PROGRAMS: ENC[AES256_GCM,data:5myvi/QyfsRtZyPDEj+q/Jokau5a+nXBYqIOCzmDrTBk8SIGgyuzmU8tsIgBCZae4pf9mcnEAtvgZI7NNHZJSPhMtUqEcJtxwDI8BEyZZAVP0xrADQ==,iv:nHbHGxhW5ITNn2cBOrtRBFtBtqH+rPtQihYU0kqQCkc=,tag:EvqS+9duaoR4DFu1j3c3eg==,type:str]
    REVIEWS_MONGODB_URL: ENC[AES256_GCM,data:MOCrbcOfMtmx6JN3yLg5HI3II2YHXGPljh9dUlIh+mTKvMSLuOtCaQw4t/802+L4HHq8WchIa6d2n8GEhsd8VowZJn/83OF7lcjgnQ==,iv:yQ7IhszW+civ3BXUnUHUPSLMzvnfcRT0vUDd3PnEs+o=,tag:+AnpsPZ8ZD3McOWfjuYuew==,type:str]
    YOTPO_APP_KEYS: ENC[AES256_GCM,data:z4LJepbt7Tiw3Ft+kQur9QWV0Nv1XiReF5YjYJVnWeHUUwnIs50yncBmtPWjWdAWquYU1wBa36SW2sSFonfv+URRGa2tY2ItKB5pDUUy8xEa85guBoRdhVT5jhPddalRHA5FfmKndgI8b5AtcMHI,iv:r58SdWaeZ3HlSMGy6FRDflYFFRjr6c6BFvTN6j9Xfbk=,tag:XuUWyx4GsEygCnNsR36vEQ==,type:str]
    YOTPO_SECRET_KEYS: ENC[AES256_GCM,data:HnorX9F9EMFCMh9qjpk70uv0GzqjAWhDU/1GEb1Ivb+eyt0kCs9+q7mC7/T1+dXEOGfAPJKS6JRiHooW42DIZXKNke+k2CgT8RtlrgjBSOfgZXAkqeprkesCIrdRUwCfWjcawty+cDvrYuf1iJnq,iv:IktfqfwGljFiZTOebo3psC0CGBzWDhiA2Hc42NawnD8=,tag:ErpFhgNQGEAQMHCqtd8cow==,type:str]
    YOTPO_PAGE_SIZE: ENC[AES256_GCM,data:kQ==,iv:dXoe7C+kdZW5VQupLxm6s1JUGLPlJEs5KIfeuh96EiY=,tag:1VR4aqjEvNVjqvOpDE135Q==,type:str]
    YOTPO_URL: ENC[AES256_GCM,data:41pGKMtU/29soxIL4DWVktJ8GXj9,iv:AMolf94Wtvi16xMJV8991O/JkUoJTb36Lnl287RcIF4=,tag:XKQauiKLpedrTeMY39DLug==,type:str]
kind: Secret
metadata:
    name: ms-catalog-zecore
    namespace: client
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-09-02T01:41:24Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wFjArHpRVpUBlpyyV75l2i7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3neNFkI4+UEboguZAgEQgDstT3aRkG9LOgFvAuBTLftfuEcaGQ9zvjM1voKiyrbtoAzE2MMOCKLLpgil1WcCk7c4rfTg0ONsFZfPDw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-26T15:48:49Z"
    mac: ENC[AES256_GCM,data:nAGgsmKbGIFv/RWiAhauNEbn5IDwTnqwKdYy/YYL52kTI2F7T82iX4wwpHmOYzOZnSC81GGszzRVEYDFEYPqXLQ60bX07+b/nGdRuuaPVrpDRWJkzTZBq19+VootaqKPvbNkLrisCz2twlvH1WOAAKI6ytgmEj/UgKE76fL1BEk=,iv:zwUn+ATez0H3ZNk78e1PSOSFStWQKMq8emLWpQ+YMKI=,tag:aTTd0I42zAsKyH1W3FMDiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
