namespace: client

generators:
  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ms-brands
      namespace: client-ms-brands
    spec:
      template:
        spec:
          containers:
          - name: ms-brands
            image: luuna/ms-brands:master-9108988950fc14d6823a2804cc5728571cee3708
  - |- 
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ms-brands
      namespace: client-ms-brands
    spec:
      minReplicas: 1
      maxReplicas: 1
