namespace: client

generators:
  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ms-catalog
      namespace: client-ms-catalog
    spec:
      template:
        spec:
          initContainers:
            - name: migrate
              image: luuna/ms-catalog:develop-154c89b25f84d1ca08aea15a235c87b1b4aef947
          containers:
            - name: ms-catalog
              image: luuna/ms-catalog:develop-154c89b25f84d1ca08aea15a235c87b1b4aef947
  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ms-catalog
      namespace: client-ms-catalog
    spec:
      minReplicas: 1
      maxReplicas: 1
