apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: client-api-b2b
  namespace: client-api
  labels:
    app: client-api-b2b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-api-b2b
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70