namespace: shipping

generators:
  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
- name: marketplace-middleware
  literals:
  - DEV_MODE=ON

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: marketplace-middleware
      namespace: marketplace-middleware
    spec:
      template:
        spec:
          containers:
            - name: marketplace-middleware
              image: luuna/marketplace-middleware:master-f112c846f4b605ee7183db5a0581a68f57ed618f
              envFrom:
                - configMapRef:
                    name: marketplace-middleware
                - secretRef:
                    name: marketplace-middleware
  - |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: marketplace-middleware
      namespace: marketplace-middleware
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: marketplace-middleware-job
                  image: luuna/marketplace-middleware:master-f112c846f4b605ee7183db5a0581a68f57ed618f
      suspend: false