apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: erpnext-redis-socketio
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis-socketio
    helm.sh/chart: redis-socketio-16.4.0
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/managed-by: Helm