apiVersion: v1
stringData:
    FLASK_APP: ENC[AES256_GCM,data:7Emu,iv:T/N6uiDZd52N53QRwz4r2UAotlnk5mr7npCsPA12t+U=,tag:hZQk4/B1EHutJ0qTDhpHHQ==,type:str]
    FLASK_ENV: ENC[AES256_GCM,data:U4mRwpdClA==,iv:rjRn87nCh/b+LnrsYME5CL/Pg6S14Pf4xUXfQ28Tp5o=,tag:DHhhRIK8jD6j/85fpdS+lg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:F/b8o5IYBOvWyq6jx/I=,iv:/NZBOkvKwhRgH5QI2HH8+3wZ7IAx1vujp5lnw94IM5E=,tag:sJN8h7ODHa0xQzfiPHYBeA==,type:str]
    BROKER_URL_ASYNC_ZECORE: ENC[AES256_GCM,data:EV5cXNEeChBXbxQ7PvYJGXUSHz9HQHbJ09lx862Amv0UUe+tdIDQLLLoK5pm860QkqaBnkOBwReGNpudOI3l9QIhdTiQsDxJYrC1KBhyTtgJP2uUUQGdrv4Q6sRPYD4n2BmE4A==,iv:/fXrEEWyUh0cZbBOKmyVXY4mDm/vVXPUmyKAMOhzRxs=,tag:UMoR1mxSp5AuQzcFPT4Q9g==,type:str]
    MS_DB_HOST: ENC[AES256_GCM,data:Q7iu/zQtv9uPOvAFDiNxQhhMELfN1KJGmzC2ZaMicz5sN3UDXDsWSvw9AXT3Mye1D1bCPTeAI3qr1vuxKlpyEg==,iv:kBPcX3nlOY3YsCCwBc2yF5m2hnDLYeqh0m9zkWQF9lA=,tag:zKTYQbRDH1UMKZd6PO618Q==,type:str]
    MS_DB_USER_NAME: ENC[AES256_GCM,data:mmipEdL3gehDt2vgrec+YESX/c2jW1czBw==,iv:i6X0KvjvKDNfPw6d5UlT/Q+BADHkrDD5AqbO+novm0g=,tag:EgF0LSWpX3h1sipvDvivEg==,type:str]
    MS_DB_PASSWORD: ENC[AES256_GCM,data:E1LA/5sgchnMqNLfMQ==,iv:ROsHAFAly7y6WeEM0ipMTuvskbY7n3o7HylC6Uc+VbU=,tag:2i0LpCbnTdmns+r/KokAvQ==,type:str]
    MS_DB_NAME: ENC[AES256_GCM,data:LeU4YaQQ4PizFyO4cv5JiYR+DOaxXvZH7g==,iv:HgKvK2D9CTlEw/ymEi3aIjpHmvMvEPvR2fRhMnsnhQw=,tag:RhpERDquttnzRRe+9XMGIQ==,type:str]
    MS_DB_PORT: ENC[AES256_GCM,data:HCdHWg==,iv:YSVH4UphlCqnT7E9FApX6Z5NG6wDMUK6sFw+Bbj69ic=,tag:iw61wMG+OmiLLm78SIaPTw==,type:str]
    SIFT_ACCOUNT_ID: ENC[AES256_GCM,data:YUMqbyofTQJJvcyts7v0YTFXb8ATZA4H,iv:QsRF6kGL/s+CzYg7uax96RjL7WrbWaqco78ikP1O4lc=,tag:tarwBylbz0jTGJtIYUJGUA==,type:str]
    SIFT_API_KEY: ENC[AES256_GCM,data:8d/4jP5UXZUaAVdMoqZW+A==,iv:Dodyll30rSW8dPbiyXv7/01ZNtuShNUp3oCUXzMrZn8=,tag:+gscCb60S4X4I7Zkzp0Vmg==,type:str]
    ATRATO_HOST: ENC[AES256_GCM,data:V3X4WDHVE6ASuj0/K0kp/6/b8YZVChjQnXL+RDMmJJ5JZA==,iv:puouWSwNKoMwx1jSxpvAHQ1AoMq/XgoKZz98iXlOjf4=,tag:82eBrROXyXOzSF35bnEsYA==,type:str]
    AWS_BUCKET: ENC[AES256_GCM,data:vKLkuSlsLxDqHNqBTScpxhh9VOT3lFA22CgYggls2rWhjPv6HEcbrO6CsHTa2eVBywvHXuo=,iv:tTC8A37CUTx0hRuY0gdU4gjfcsbmj8sBTXNx6tQvmbk=,tag:tol4IVER80Dv3ED5GGj8sQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:njSIaImZFL8spbDmBTlW5I0EGy0=,iv:xaYnOsBii6dBQUtWHV2YdHUHBNM96HyoQTXNh7Tx3yg=,tag:TdCRCP3ErDZ8+gFf5B6iEw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BUcc2jwaBmqJhaS3Rv8WZRBHlthQI8poOU9eEvt7qH/WIiR25EwnFw==,iv:x707Vu232SMQYlW6rN6oi7qnSsUEes9paFsbLLARk60=,tag:PeB/49VNsEQzKRY4CD7qJw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:hRfOTva6YMhQ,iv:5TTwUGh5hIOc04l76wnosw2vn+556ns+Bqrw6ae3PX0=,tag:VdMj18ZvXlh0Ijr1/7s/8Q==,type:str]
    STP_HOST: ENC[AES256_GCM,data:pI7cvf1gJnMQyyyFsh5DBd3tty+AHASKbxOINRnDEKn85JCI,iv:oPUqEGkr6biHpluBu4hTMjWX5DUAKl8Ns42Y855tj78=,tag:4TQ4y05nJoSTgJcjlbqHew==,type:str]
kind: Secret
metadata:
    name: payment-gateway-providers
    namespace: payments
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-28T22:45:04Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wF+C8FqgSZEHp4ex4LNhxa9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf6m8xsYZkKGV7kQ1AgEQgDs7ECThWoMp0HVEr+kgRmaYtB1TBxh8O+Z5k1y0qer2e5MItLIQNWgGaz0ocCv4ryjCQAKWCdmDZymRbA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-22T21:58:49Z"
    mac: ENC[AES256_GCM,data:gIqrAOUX0t4qW86sg47N9P01lL42rEh5cCZNaWRNOe7sxkMKaakF3rgGJYWyu26qMwlTsCj8uGEBFPL9W0QfCQJ3J5JDXw4wxyUS1wY/6UNKkV5PF+6BppNWI2BE5q7AD1XTXniqXNntC8GLTZM+vmFCvBgTW8/OBN/a2rsChbA=,iv:FIIxXkajLjC3MOr+GmgsPwR+3IDQcksjXn350PoetcM=,tag:i5vHhmrdQdv3qf7LM13dSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
