kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: erpnext
    chart: erpnext-3.2.36
    heritage: Helm
    release: erpnext
  name: erpnext
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
  storageClassName: efs-sc