namespace: payments

generators:
  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: payment-gateway-providers
      namespace: payments
    spec:
      template:
        spec:
          initContainers:
          - name: migrations
            image: luuna/payment-gateway-providers:master-b9c2dbe9029f1aa8f7d291a169ba5c6e44fd0806
          containers:
          - name: payment-gateway-providers
            image: luuna/payment-gateway-providers:master-b9c2dbe9029f1aa8f7d291a169ba5c6e44fd0806
          hostAliases:
          - ip: "10.5.1.1"
            hostnames:
            - "prod.stpmex.com"

  #Subnet Public for Load Balancer [10.0.0.0/20]
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: svc-vpn-site-to-site
      namespace: payments
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
        service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0da4439bd41c13665
        service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0ec4b5ad52c6193d0"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:027984065276:certificate/40073a3f-250f-41bd-bd76-6cd850cdffcf
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  