apiVersion: v1
stringData:
    FLASK_APP: ENC[AES256_GCM,data:7Emu,iv:T/N6uiDZd52N53QRwz4r2UAotlnk5mr7npCsPA12t+U=,tag:hZQk4/B1EHutJ0qTDhpHHQ==,type:str]
    FLASK_ENV: ENC[AES256_GCM,data:XKEvZcGdr9lL9w==,iv:lN3OyaxpVXuUxLkJ+MU0wVYi3zmaLqc08IrZAu0i5jE=,tag:YFRmOXRKn8KO8pa9QROd4A==,type:str]
    DEBUG: ENC[AES256_GCM,data:tNa6NiI=,iv:UXu5aMAaEIFDrKhWRR6yiDSkglCMHcbk5li3v4XnXM4=,tag:tc6eJo/YbOs1Won7GFqm8A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:iUsbSZ24bVJ6l7p8fFmEEgPgJAUowLhkg6h6qErmpO32K4g=,iv:aXpfGIbQO09p6uTFCeiCYR8OiLpulWvw1zsYFdGLGyI=,tag:N26tAl1/7jHJZPB0eWR3HQ==,type:str]
    BROKER_URL_ASYNC_ZECORE: ENC[AES256_GCM,data:xfbIj+NcH80EzXuodNuUfkyW1Jdo5IypLkAYfKbyIntd4xVX5RmWThGldSkBKnAWBYRRn487HYT5l6lAu5sus22XzFJhUmQYHLP4QhUqP1xZhBXWv69osLXFJGLSu1tP,iv:p2VVqKbIAvNZ/K3ZTpUPI8qD6SXFUJfm64xKy9+y4Pk=,tag:J4ce0IZiTxjtK/iuqXUmdA==,type:str]
    MS_DB_HOST: ENC[AES256_GCM,data:S1qvoeeYEdEUtE9Z67NdHF2TiIR7l1Uz7nymQmIGBQFGSme8Pw9j7ypXrOaIMJvFqKn/aKIcSmZh9ZnY0IEeumkaKQ==,iv:VRw7h0A/kz0YQs1nMYWkvCZNuf74aFOsc8/SLLNb3FA=,tag:Kn9n2e5g3XuUfbmgJDgVgA==,type:str]
    MS_DB_USER_NAME: ENC[AES256_GCM,data:mmipEdL3gehDt2vgrec+YESX/c2jW1czBw==,iv:i6X0KvjvKDNfPw6d5UlT/Q+BADHkrDD5AqbO+novm0g=,tag:EgF0LSWpX3h1sipvDvivEg==,type:str]
    MS_DB_PASSWORD: ENC[AES256_GCM,data:nWi4Px1Q+tRnQ2qZhmMLwA==,iv:n/Si3SyhpD2aBeVV8SUZWbcsz4x41+w9WGQz28MxpJA=,tag:njpD1xONdZS0pG0FSb+5mA==,type:str]
    MS_DB_NAME: ENC[AES256_GCM,data:LeU4YaQQ4PizFyO4cv5JiYR+DOaxXvZH7g==,iv:HgKvK2D9CTlEw/ymEi3aIjpHmvMvEPvR2fRhMnsnhQw=,tag:RhpERDquttnzRRe+9XMGIQ==,type:str]
    MS_DB_PORT: ENC[AES256_GCM,data:HCdHWg==,iv:YSVH4UphlCqnT7E9FApX6Z5NG6wDMUK6sFw+Bbj69ic=,tag:iw61wMG+OmiLLm78SIaPTw==,type:str]
    SIFT_API_KEY: ENC[AES256_GCM,data:7v6EnWzeM5h7J+H4ZdLmfg==,iv:J+zRDpr8lYZUCEP5PGrkhaICYG++ALFXtOrf5lcxMaI=,tag:x0RxcT8Q4b7Q1+DZLXpx5Q==,type:str]
    SIFT_ACCOUNT_ID: ENC[AES256_GCM,data:KBlKE4OmbdpaGBvl2FsnvyWn7lx87bDk,iv:SXXxJYrADp5Z5IDp1I1Cv3eiIPuOYMcys8XuAGq9B+c=,tag:OJ55YnWtFfD35PmZSaww4w==,type:str]
    ATRATO_HOST: ENC[AES256_GCM,data:7cF+lI4XjF9F09d2ot3QDRXlFpO5rKIY9HQ=,iv:/y3+FZwSj7/Rk+6WmKe7uTc2iEc19EFS6Css64Tl73A=,tag:/6iGJ8yKpeXpdSBfRjXIQg==,type:str]
    PAYPAL_HOST: ENC[AES256_GCM,data:+mbMGFZYXydQWdBPI3XHlEl3KK8nCQ==,iv:lgovPRfoKYyKVXkQV8X0+T+xGNxDrZdCExBPyYQRMq4=,tag:vIYB5kTiozoAhesVjIavRw==,type:str]
    SEGMENT_WRITE_KEY: ENC[AES256_GCM,data:REgV6i6Y9Qf4sVSJJYgbmip0R10hqcrFS8HO9nqt5BqsuC4A3n4uF4/rXzuju17aN8AjSX5qbKmNKw+7tj0nprq4BQOiJDVEc9QlSowdpPcMerpX5tcJ,iv:9//CzVfy2ic9MZLLKVR/ACKqfIYB+loUo8pQG6tnhT8=,tag:/g3wLnpiAnVrUscDmJ0J5g==,type:str]
    AWS_BUCKET: ENC[AES256_GCM,data:9g0IUg/JZgKEAcawxbwebIoR1FiQqvDwyKGxX8CCIsE8pEAtzC6sN3ZIOTa+H/zxbAhqMttj1N4=,iv:wqJw0HynERu7UmZ3/5JE1SZoXuQza3TA6kFq2jZGaAc=,tag:7dMmnYiDgVmr02Mv4Ye/rg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JFAlDlAtdCjgT9d8AWzHS6jhn6A=,iv:lPqx1cEbyzUA3NoBTyVXDcadk+/z8RJ+WYp2Wvilhpg=,tag:ZRnpRek3Rlhdw4a7/AuWKQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OHo3BlJGnrqobDtW95/kHIvJEYtuvoaGL0+TPDtinUegwswqOrrG/g==,iv:eNtP2fkPgr/fBEC4KT04BC4iFnFleB4AiFaeXz7Ayt8=,tag:Wo1tUEQsEpFgpMrGBn9UbA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:j/rU9sDQS3md,iv:/whpx42TAXw/LHs6+ocCzHg+YqUMftygSxX8xhf9bhI=,tag:9OU4o4me+i5ZY34mm3TJdA==,type:str]
    STP_HOST: ENC[AES256_GCM,data:UE3bicKiRhngYdzzH7fa7w12PKX8LDTuTddGkfYm108u10lBdA==,iv:lSHJh34aDSo3pTdKE3lUcEgIPT7ip2PLAEwAHsA4ZVE=,tag:nQLXJTkvgU29z6LPVcrwjA==,type:str]
kind: Secret
metadata:
    name: payment-gateway-providers
    namespace: payments
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-28T22:45:04Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wF+C8FqgSZEHp4ex4LNhxa9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf6m8xsYZkKGV7kQ1AgEQgDs7ECThWoMp0HVEr+kgRmaYtB1TBxh8O+Z5k1y0qer2e5MItLIQNWgGaz0ocCv4ryjCQAKWCdmDZymRbA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-27T18:12:52Z"
    mac: ENC[AES256_GCM,data:2XeO8qEMNidsV9O1Y8DsCBvDEapbnEpOIHRypDvN6WofDQs8QutAfFJJvcJGcx89vo62hDBv+uTAQx0g1+uZcbOLrIvZ9HqGOHpwCDydpDeL6xYkyGY3a35+H3zMY9/GyCdh54jpLYgyH7Ra4JTYkcwqFkfCSk+3S4yu3Kj6Wv8=,iv:fGTmZldWP+vXmjovdFIMq+VCVrfGxqk78P6ifc+qu8Y=,tag:03xq5X4h4H50qMLGLgkTXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
