resources:
  - ../../base
  - ingress.yaml

namespace: client

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: gateway
    literals:
      - APP_PORT="5000"
      - PLAYGROUND="false"
      - MS_AUTH=http://ms-auth.client.svc.cluster.local/graphql
      - MS_BRANDS=http://ms-brands.client.svc.cluster.local/graphql
      - MS_CATALOG=http://ms-catalog.client.svc.cluster.local/graphql
      - MS_REVIEWS=http://ms-reviews.client.svc.cluster.local/graphql
      - REWARDS_URL=https://rewards-api.luuna.mx

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gateway
      namespace: client-gateway
    spec:
      template:
        spec:
          containers:
          - name: gateway
            image: luuna/gateway:master-1c7ffc8730d6ace8739867d3ecd0eaec996ca0c2
  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: gateway
      namespace: client-gateway
    spec:
      minReplicas: 5
      maxReplicas: 80
