apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "True"
    #nginx.ingress.kubernetes.io/from-to-www-redirect: "True"
    #nginx.ingress.kubernetes.io/server-snippet: |
    #  location ~* "^/" {
    #    proxy_pass https://d1crvq4zuhdsef.cloudfront.net/503_luuna/index.html?$1;
    #    proxy_set_header X-Real-IP $remote_addr;
    #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header X-Forwarded-Proto $scheme;
    #  }
  name: web-client-luuna-zecore
  namespace: web-client
spec:
  rules:
    - host: zecore-development.luuna.mx
      http:
        paths:
          - backend:
              service:
                name: web-client-luuna-zecore
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific


