apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::027984065276:role/zeb-backend-develop20220128194358995800000009"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::027984065276:user/mauricio"
      "username": "mauricio"
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::027984065276:user/carlos.rios@zeb.mx"
      "username": "carlos.rios"
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::027984065276:user/maximiliano.salamone@zeb.mx"
      "username": "maximiliano.salamone"
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::027984065276:user/cristhian.monasterios@zeb.mx"
      "username": "cristhian.monasterios"
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::027984065276:user/yancel.salinas@zeb.mx"
      "username": "yancel.salinas"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/alfonso.sanchez@zeb.mx"
      "username": "alfonso.sanchez"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/valter.nunez@zeb.mx"
      "username": "valter.nunez"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/ingrid.rodriguez@zeb.mx"
      "username": "ingrid.rodriguez"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/eduardo.flores@zeb.mx"
      "username": "eduardo.flores"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/alma.patino@zeb.mx"
      "username": "alma.patino"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/bernardo.laing@zeb.mx"
      "username": "bernardo.laing"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/steve"
      "username": "steve.beltran"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/nicolas.rodriguez@zeb.mx"
      "username": "nicolas.rodriguez"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/erick.samaniego@zeb.mx"
      "username": "erick.samaniego"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/reynier.claro@zeb.mx"
      "username": "reynier.claro"
    - "groups":
      - "system:none"
      "userarn": "arn:aws:iam::027984065276:user/marlon.inga@zeb.mx"
      "username": "marlon.inga"
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
  name: aws-auth
  namespace: kube-system

