apiVersion: batch/v1
kind: CronJob
metadata:
  name: zefin-middleware-kyc-db
  namespace: zefin
spec:
  schedule: 0 9 * * *
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron: zefin-middleware-kyc-backup
        spec:
          restartPolicy: OnFailure
          containers:
            - name: zefin-middleware-kyc-backup
              image: postgres:13-alpine3.16
              envFrom:
              - secretRef:
                  name: zefin-middleware-kyc
              args:
                - /bin/sh
                - -c
                - |
                  apk -v --update add --no-cache py-pip openssh-client 
                  pip install --upgrade pip
                  pip install --upgrade awscli==1.25.11 s3cmd==2.0.1 python-magic
                  rm -f /var/cache/apk/*
                  cd /tmp/
                  echo "Backup started for database - ${MS_DB_NAME}"
                  FILE=`date +%Y%m%d_%H%M%S`_${MS_DB_NAME}.sql
                  PGPASSWORD=$MS_DB_PASSWORD pg_dump --no-owner -h ${MS_DB_HOST} -p ${MS_DB_PORT} -U ${MS_DB_USER_NAME} ${MS_DB_NAME} > $FILE;
                  tar -czvf $FILE.tar.gz $FILE
                  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_BACKUP
                  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_BACKUP
                  aws s3 cp $FILE.tar.gz $AWS_BUCKET_BACKUP
                  rm $FILE && rm $FILE.tar.gz
                  echo "Dump SQL completed"  
  successfulJobsHistoryLimit: 3
  suspend: false