apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-client-graphql
    service: ms-client-graphql
  name: ms-client-graphql
  namespace: client
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: ms-client-graphql
  type: ClusterIP
