namespace: testing

generators:
  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
- name: marketplace-middleware
  literals:
  - DEV_MODE=ON
  - NEST_DEBUG=true

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: marketplace-middleware
      namespace: marketplace-middleware
    spec:
      template:
        spec:
          containers:
            - name: marketplace-middleware
              image: luuna/marketplace-middleware:refactor-restructure_schema-566193165f0f244c9c3d3ca1c609fd887366bde1
              envFrom:
                - configMapRef:
                    name: marketplace-middleware
                - secretRef:
                    name: marketplace-middleware

  - |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: marketplace-middleware
      namespace: marketplace-middleware
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: marketplace-middleware-job
                  image: luuna/marketplace-middleware:refactor-restructure_schema-566193165f0f244c9c3d3ca1c609fd887366bde1