---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pedro.rodriguez
  namespace: client
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/portforward
  - pods/log
  - configmaps
  - secrets
  - services
  - services/portforward
  - services/log
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pedro.rodriguez
  namespace: client
subjects:
- kind: User
  name: pedro.rodriguez
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: yancel.salinas
  apiGroup: rbac.authorization.k8s.io
