apiVersion: v1
kind: Service
metadata:
  name: erpnext-redis-cache
  namespace: erpnext
spec:
  type: ClusterIP
  ports:
    - port: 13000
      targetPort: 6379
  selector:
    app.kubernetes.io/name: erpnext-redis-cache
    app.kubernetes.io/instance: erpnext-redis-cache