apiVersion: v1
kind: Service
metadata:
  name: erpnext-redis-socketio
  namespace: erpnext
spec:
  type: ClusterIP
  ports:
    - port: 11000
      targetPort: 6379
  selector:
    app.kubernetes.io/name: erpnext-redis-socketio
    app.kubernetes.io/instance: erpnext-redis-socketio