apiVersion: v1
kind: Service
metadata:
  name: erpnext
  namespace: erpnext
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: erpnext-backend
    app.kubernetes.io/instance: erpnext-backend