apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zefin-loan-origination-system
  name: zefin-loan-origination-system
  annotations:
    configmap.reloader.stakater.com/reload: "zefin-loan-origination-system"
    secret.reloader.stakater.com/reload: "zefin-loan-origination-system" 
  namespace: zefin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zefin-loan-origination-system
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:   
      labels:
        app: zefin-loan-origination-system
    spec:                   
      containers:
        - name: zefin-loan-origination-system
          image: luuna/zefin-loan-origination-system:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: zefin-loan-origination-system         
          - secretRef:
              name: zefin-loan-origination-system
          #readinessProbe:
          #  httpGet:
          #    path: /_health
          #    port: 8000
          #    scheme: HTTP
          #  failureThreshold: 5
          #  successThreshold: 1
          #  periodSeconds: 10
          #  timeoutSeconds: 7              
          resources:
            requests:
              memory: "100Mi"
              cpu: "150m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /tmp
              name: app          
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 10000
            runAsUser: 10000
      volumes:
      - name: app
        emptyDir: {}            
      enableServiceLinks: true
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        purpose: backend
      restartPolicy: Always
      serviceAccount: zefin-loan-origination-system
      serviceAccountName: zefin-loan-origination-system
