apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: erpnext-redis-cache
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis-cache
    helm.sh/chart: redis-cache-16.4.0
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/managed-by: Helm