apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: client-api-luuna
  namespace: client-api
spec:
  rules:
    - host: api-development.luuna.mx
      http:
        paths:
          - backend:
              service:
                name: client-api-luuna
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
