apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: web-client-nooz-zecore
  namespace: web-client
spec:
  rules:
    - host: zecore-staging.nooz.mx
      http:
        paths:
          - backend:
              service:
                name: web-client-nooz-zecore
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific


