apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-and-push-job
  namespace: erpnext
spec:
  schedule: 0 5 * * *
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: true
          containers:
          - name: push-backup
            image: luuna/erpnext-worker:master-latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: s3
            - configMapRef:
                name: erpnext
            args:
            - push-backup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /home/frappe/frappe-bench/sites
              mountPropagation: None
              name: sites-dir
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          imagePullSecrets:
          - name: docker-creds
          initContainers:
          - name: backup
            args:
            - backup
            env:
            - name: WITH_FILES
              value: "1"
            image: luuna/erpnext-worker:master-latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: mariadb
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /home/frappe/frappe-bench/sites
              mountPropagation: None
              name: sites-dir
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsNonRoot: false
            supplementalGroups:
            - 1000
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
          volumes:
          - name: sites-dir
            persistentVolumeClaim:
              claimName: erpnext
  successfulJobsHistoryLimit: 3
  suspend: false
