apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-client-nooz
  namespace: web-client
spec:
  podSelector:
    matchLabels:
      app: web-client-nooz
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: web-client-nooz
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
