loki:
  enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClassName: efs-sc
    size: 150Gi

promtail:
  enabled: true

grafana:
  enabled: false

prometheus:
  enabled: false
