apiVersion: v1
stringData:
    SAP_DB: ENC[AES256_GCM,data:RM/ENVixpVN349I=,iv:Nn/zOCChFmJUPXhleGjjJjt2gDCFXlFQMyiDb/1+0N0=,tag:zRnNGTwwWLkvDpcSbZkM8g==,type:str]
kind: Secret
metadata:
    name: client-api-pos-nooz
    namespace: client-api
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-04T05:33:57Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wEii4Ew2+ws0tRjc7KIQnUwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkUj/drdOLMd7bpaLAgEQgDs+qlv4m5cEjiEjVG71DsRsYBKwTXLCogpXClYiRRs0nKngntaXZuZbgQbhrWnM/OEJU/wEsAvNVP83vg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-26T00:34:53Z"
    mac: ENC[AES256_GCM,data:BgfBTidcHFtNiWsIvBC1ayCAVG5hYS5/B/7SmJqLUokKDxQzJb19cZaaa0Z2eGFyKDG7SXJ+PWqUN/sNHDnmrb6m5N4c3k3KXl46ClRnMz05B/pgWAmOiPtE/9bAjCix3iD1hBcKcYpesiNIDT6sGjsp3uDifbZFFWEnjJQ8Rxk=,iv:UrkrYpIeF2smb8nQZmBTeoAzh4JcGMNgu4vZVhM0dqw=,tag:60wlo/Dh4VGPmj6huU6rkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
