apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ms-client-graphql
  namespace: client
spec:
  rules:
    - host: ms-client-zecore-staging.luuna.mx
      http:
        paths:
          - backend:
              service:
                name: ms-client-graphql
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
