apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-api-pos-luuna
    service: client-api-pos-luuna
  name: client-api-pos-luuna
  namespace: client-api
spec:
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
  selector:
    app: client-api-pos-luuna
  type: ClusterIP
