apiVersion: v1
stringData:
    SAP_HOST: ENC[AES256_GCM,data:WC+32dKMkQadcQU=,iv:Zr/s1FOE14BmowzWmfVmArNpG/kdmbGurGc36vwrKUA=,tag:fVXCy7PZ8jVlcHDfJxqbFg==,type:str]
    SAP_PASSWORD: ENC[AES256_GCM,data:DUPFpSe9ayYpETrPHkA6aQ==,iv:lmSsW68uFGsjFv8IjAGXfN6WKPiibbpGEDvfhDFjNEg=,tag:IG2i/5XuGxpbrgEteiCW0w==,type:str]
    ALBA_BROKER_URL: ENC[AES256_GCM,data:FJZ55n0cXfCMWNjvXoi+XI0qCr/SsGcAgaVz/Y8q1BzmqC3p8luBD0cSgoxtjAdG84KTVwjTsuI6+90/npSakwQKt6ehJucg1HXd2Fs6rGywTgY=,iv:rG0eHbaUKTq+MnC6hclBPsGIcLV0AbL4eWUB6aJkqv8=,tag:v5YdclEFFJ17Njc7R0st8Q==,type:str]
kind: Secret
metadata:
    name: client-api-pos-luuna
    namespace: client-api
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-04T05:33:57Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wEii4Ew2+ws0tRjc7KIQnUwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkUj/drdOLMd7bpaLAgEQgDs+qlv4m5cEjiEjVG71DsRsYBKwTXLCogpXClYiRRs0nKngntaXZuZbgQbhrWnM/OEJU/wEsAvNVP83vg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-26T00:53:33Z"
    mac: ENC[AES256_GCM,data:eUeVZ4SH/2V7yFesjcfdq2Vyty02QbXzCtNOyijROY3cc/qta9osEIznYZeShAaHQLd1B7J02xULPujSNOJ9G3Des2FF0FaA4IiUBmwp4DZdllbpg5Dlk6J2IgR1V+CTNp8v6u/Tby4lxRr1fmLea9ka5m0iHYyFsLf9AumOhiA=,iv:swRI8m4fOUD0WuVnXUzLzuQsdOJzrdFg3WKH4nrQ3tI=,tag:tLmNurxc3KtGhH3qu/vHqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
