apiVersion: v1
stringData:
    SAP_HOST: ENC[AES256_GCM,data:ZgdfqYSIGuaJT950,iv:b2eSpeA2+PDcGAFmKoD0JNuU1HpenSnyiWZmGZKOsU0=,tag:Lzj3nyASpsKv2Xdc18bYrw==,type:str]
    SAP_PASSWORD: ENC[AES256_GCM,data:PFPqKAy6C8UGhBaSqJfDqA==,iv:ZwKJZwXL4GnT0J1/VirBY9DlfUO61emTTcB0weBYZFo=,tag:e+VS+C8j57PycbYM5K7/nA==,type:str]
kind: Secret
metadata:
    name: client-api-pos-nooz
    namespace: client-api
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-04T05:33:57Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wEii4Ew2+ws0tRjc7KIQnUwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkUj/drdOLMd7bpaLAgEQgDs+qlv4m5cEjiEjVG71DsRsYBKwTXLCogpXClYiRRs0nKngntaXZuZbgQbhrWnM/OEJU/wEsAvNVP83vg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-26T00:47:09Z"
    mac: ENC[AES256_GCM,data:ZoZlnzMqG1Jux9KrZ6Dpuooo2PWnW2gRPm7lhQRn79hIWVx3DhOg+5iaSO8mF5SO8Mwg7XaDmEN/tfP+SUJ6Moimo3mU4VL6ARPD7hWS/gYlDHQ/hgBma21v54FxTp88LJFCnn/5dFDUJzhvJoN5H1++Pt3AXl1NHXfi9lD1b/0=,iv:/SHU3SvSr06Egfs5aH9fRjmVqXW8GYA4PK3gwezayvg=,tag:oFbBFTXY9gvNJYDKZ3zaqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
