apiVersion: v1
kind: Service
metadata:
  name: link-iterable-luuna-zecore
  namespace: web-client
spec:
  ports:
    - port: 80
  type: ExternalName
  externalName: links.iterable.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: link-interable-luuna-zecore
  namespace: web-client
spec:
  rules:
    - host: links.luuna.mx
      http:
        paths:
          - backend:
              service:
                name: link-iterable-luuna-zecore
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific

