apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-api-nooz
    service: client-api-nooz
  name: client-api-nooz
  namespace: client-api
spec:
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
  selector:
    app: client-api-nooz
  type: ClusterIP
