apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ms-client-graphql
  namespace: client
spec:
  podSelector:
    matchLabels:
      app: ms-client-graphql
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ms-client-graphql
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 6379