namespace: payments

generators:
  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zecore-async-entrypoint
      namespace: payments
    spec:
      template:
        spec:
          containers:
          - name: zecore-async-entrypoint
            image: luuna/zecore-async-entrypoint:staging-caf74f146a359b7547584b2b2591e028fd805c4d
          - name: zecore-async-entrypoint-api
            image: luuna/zecore-async-entrypoint:staging-caf74f146a359b7547584b2b2591e028fd805c4d