apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-redis-socketio
  namespace: erpnext
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: erpnext-redis-socketio
      app.kubernetes.io/instance: erpnext-redis-socketio
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erpnext-redis-socketio
        app.kubernetes.io/instance: erpnext-redis-socketio
    spec:
      nodeSelector:
        purpose: redis
      serviceAccountName: erpnext-redis
      containers:
      - name: master
        image: "bitnami/redis:5.0.10-debian-10-r105"
        imagePullPolicy: Always
        command: ["redis-server"]
        args: ["--bind 0.0.0.0"]
        resources:
        env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
