apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-erpnext
  namespace: erpnext
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: erpnext-backend
      app.kubernetes.io/instance: erpnext-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erpnext-backend
        app.kubernetes.io/instance: erpnext-backend
        frappe-component: erpnext-backend
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9113'
        prometheus.io/scrape: 'true'        
    spec:
      nodeSelector:
        purpose: erpnext
      imagePullSecrets:
        - name: docker-creds
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.9.0
          args:
            - "-nginx.scrape-uri=http://localhost:88/nginx_status" 
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 3m
              memory: 15Mi
          imagePullPolicy: Always        
        - name: erpnext-assets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - CAP_CHOWN
            runAsUser: 0
          image: "luuna/erpnext-nginx:latest-develop"
          volumeMounts:
          - name: assets-cache
            mountPath: /assets
          - name: sites-dir
            mountPath: /var/www/html/sites
          imagePullPolicy: Always
          env:
            - name: "FRAPPE_PY"
              value: "0.0.0.0"
            - name: "FRAPPE_PY_PORT"
              value: "8000"
            - name: "FRAPPE_SOCKETIO"
              value: erpnext-socketio
            - name: "SOCKETIO_PORT"
              value: "9000"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 120Mi
            requests:
              cpu: 100m
              memory: 80Mi
        - name: erpnext-python
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - CAP_CHOWN
            runAsUser: 0
          image: "luuna/erpnext-worker:latest-develop"
          volumeMounts:
          - name: assets-cache
            mountPath: /home/frappe/frappe-bench/sites/assets
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
          imagePullPolicy: Always
          env:
            - name: "DB_PORT"
              value: "3306"
            - name: "REDIS_QUEUE"
              value: erpnext-redis-queue:12000
            - name: "REDIS_CACHE"
              value: erpnext-redis-cache:13000
            - name: "REDIS_SOCKETIO"
              value: erpnext-redis-socketio:11000
            - name: "SOCKETIO_PORT"
              value: "9000"
          envFrom:
          - secretRef:
              name: mariadb
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1500m
              memory: 3000Mi
            requests:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: assets-cache
          emptyDir: {}
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
        - name: logs
          emptyDir: {}
