apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-worker-d
  namespace: erpnext
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: erpnext-worker-d
      app.kubernetes.io/instance: erpnext-worker-d
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erpnext-worker-d
        app.kubernetes.io/instance: erpnext-worker-d
        frappe-component: erpnext-worker
        erpnext-worker: default
    spec:
      nodeSelector:
        purpose: worker
      imagePullSecrets:
        - name: docker-creds
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      terminationGracePeriodSeconds: 3600
      containers:
        - name: erpnext
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - CAP_CHOWN
            runAsUser: 0
          image: "luuna/erpnext-worker:latest-develop"
          volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
          imagePullPolicy: Always
          args: ["worker"]
          env:
            - name: "WORKER_TYPE"
              value: "default"
          livenessProbe:
            exec:
              command:
              - "healthcheck.sh"
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - "healthcheck.sh"
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
        - name: logs
          emptyDir: {}
