resources:
  - ../../base
  - ingresses
  - iterable

namespace: client

configMapGenerator:
  - name: luuna-sitemap-zecore
    files:
      - sitemap.xml=luuna.sitemap.xml
  - name: nooz-sitemap-zecore
    files:
      - sitemap.xml=nooz.sitemap.xml
  - name: mappa-sitemap-zecore
    files:
      - sitemap.xml=mappa.sitemap.xml  

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-client-luuna-zecore
      namespace: web-client
    spec:
      template:
        spec:
          containers:
            - name: web-client
              image: luuna/web-v2-luuna:zecore-production-9749a418c09325e45bbb3de2347cfc0ec0cfeb14
  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: web-client-luuna-zecore
      namespace: web-client
    spec:
      minReplicas: 30
      maxReplicas: 150
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-client-nooz-zecore
      namespace: web-client
    spec:
      template:
        spec:
          containers:
            - name: web-client
              image: luuna/web-v2-nooz:zecore-production-9749a418c09325e45bbb3de2347cfc0ec0cfeb14
  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: web-client-nooz-zecore
      namespace: web-client
    spec:
      minReplicas: 5
      maxReplicas: 20

  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-client-mappa-zecore
      namespace: web-client
    spec:
      template:
        spec:
          containers:
            - name: web-client
              image: luuna/web-v2-mappa:zecore-production-9749a418c09325e45bbb3de2347cfc0ec0cfeb14

  - |-
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: web-client-mappa-zecore
      namespace: web-client
    spec:
      minReplicas: 5
      maxReplicas: 100
