apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ms-onfleet
  namespace: shipping
spec:
  schedule: 0 5 * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron: ms-onfleet-backup
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ms-onfleet-job
              image: postgres:13-alpine3.16
              envFrom:
              - secretRef:
                  name: ms-onfleet
              args:
                - /bin/sh
                - -c
                - |
                  apk -v --update add --no-cache py-pip openssh-client 
                  pip install --upgrade pip
                  pip install --upgrade awscli==1.25.11 s3cmd==2.0.1 python-magic
                  rm -f /var/cache/apk/*
                  cd /tmp/
                  echo "Backup started for database - ${POSTGRES_DB}"
                  FILE=`date +%Y%m%d_%H%M%S`_${POSTGRES_DB}.sql
                  PGPASSWORD=$POSTGRES_PASSWORD pg_dump --no-owner -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER} ${POSTGRES_DB} > $FILE;
                  tar -czvf $FILE.tar.gz $FILE
                  aws s3 cp $FILE.tar.gz $AWS_BUCKET
                  rm $FILE && rm $FILE.tar.gz
                  echo "Dump SQL completed"
