---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-zecore
  namespace: web-client
data:
  nginx.conf: |
    user  nginx;
    worker_processes  2;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
      include   /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      proxy_cache_path 
        /var/cache/nginx 
        levels=1:2 
        keys_zone=STATIC:10m 
        inactive=7d 
        use_temp_path=off;

      upstream webclient_upstream {
        server localhost:8080;
      }

      server {
        listen 8000 default_server;

        server_name _;

        server_tokens off;

        gzip on;
        gzip_proxied any;
        gzip_comp_level 4;
        gzip_types text/html text/plain text/css application/javascript image/svg+xml;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        location /_next/static {
          proxy_buffering on;
          proxy_cache STATIC;
          proxy_pass http://webclient_upstream;

          # For testing cache - remove before deploying to production
          add_header X-Cache-Status $upstream_cache_status;
        }

        location /static {
          proxy_cache STATIC;
          proxy_ignore_headers Cache-Control;
          proxy_cache_valid 60m;
          proxy_pass http://webclient_upstream;

          # For testing cache - remove before deploying to production
          add_header X-Cache-Status $upstream_cache_status;
        }

        location = /sitemap.xml {
          root /statics;
        }

        location / {
          proxy_pass http://webclient_upstream;
        }
      }
    }
