apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-reviews
  namespace: client-ms-reviews
  labels:
    app: ms-reviews
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-reviews
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70