apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-gunicorn
  labels:
    helm.sh/chart: erpnext-5.0.20
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/version: "v14.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: erpnext-gunicorn
      app.kubernetes.io/instance: erpnext-gunicorn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erpnext-gunicorn
        app.kubernetes.io/instance: erpnext-gunicorn
    spec:
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      initContainers:
        - name: populate-assets
          image: "frappe/erpnext-nginx:v14.2.0"
          imagePullPolicy: IfNotPresent
          command:
            - cp
            - -fR
          args:
            - /usr/share/nginx/html/assets
            - /home/frappe/frappe-bench/sites
          securityContext:
            capabilities:
              add:
              - CAP_CHOWN
          volumeMounts:
            - name: assets-cache
              mountPath: /home/frappe/frappe-bench/sites/assets
      containers:
        - name: gunicorn
          args:
            - /home/frappe/frappe-bench/env/bin/gunicorn
            - --bind=0.0.0.0:8000
            - --config=/opt/patches/gevent_patch.py
            - --log-file=-
            - --preload
            - --threads=4
            - --timeout=120
            - --worker-class=gevent
            - --worker-tmp-dir=/dev/shm
            - --workers=2
            - frappe.app:application
          securityContext:
            capabilities:
              add:
              - CAP_CHOWN
          image: "frappe/erpnext-worker:v14.2.0"
          volumeMounts:
          - name: assets-cache
            mountPath: /home/frappe/frappe-bench/sites/assets
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 8000
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 8000
          resources:
            {}
      volumes:
        - name: assets-cache
          emptyDir: {}
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
        - name: logs
          emptyDir: {}