apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-nginx
  labels:
    helm.sh/chart: erpnext-5.0.20
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/version: "v14.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: erpnext-nginx
      app.kubernetes.io/instance: erpnext-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erpnext-nginx
        app.kubernetes.io/instance: erpnext-nginx
    spec:
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      containers:
        - name: nginx
          env:
            - name: "BACKEND"
              value: erpnext-gunicorn:8000
            - name: "SOCKETIO"
              value: erpnext-socketio:9000
            - name: "UPSTREAM_REAL_IP_ADDRESS"
              value: "127.0.0.1"
            - name: "UPSTREAM_REAL_IP_RECURSIVE"
              value: "off"
            - name: "UPSTREAM_REAL_IP_HEADER"
              value: X-Forwarded-For
            - name: "FRAPPE_SITE_NAME_HEADER"
              value: $host
          image: "frappe/erpnext-nginx:v14.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 8080
          resources:
            {}
          securityContext:
            capabilities:
              add:
              - CAP_CHOWN
          volumeMounts:
          - name: sites-dir
            mountPath: /usr/share/nginx/html/sites
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false