apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext-worker-l
  labels:
    helm.sh/chart: erpnext-5.0.20
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/version: "v14.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: erpnext-worker-l
      app.kubernetes.io/instance: erpnext-worker-l
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erpnext-worker-l
        app.kubernetes.io/instance: erpnext-worker-l
    spec:
      serviceAccountName: erpnext
      securityContext:
        supplementalGroups:
        - 1000
      containers:
        - name: long
          args:
          - bench
          - worker
          - --queue
          - long
          image: "frappe/erpnext-worker:v14.2.0"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            
            exec:
              command:
                - bash
                - -c
                - echo "Ping backing services";
                - wait-for-it erpnext-mariadb:3306 -t 1;
            initialDelaySeconds: 15
            periodSeconds: 5
            
          readinessProbe:
            
            exec:
              command:
                - bash
                - -c
                - echo "Ping backing services";
                - wait-for-it erpnext-mariadb:3306 -t 1;
            initialDelaySeconds: 15
            periodSeconds: 5
            
          resources:
            {}
          securityContext:
            capabilities:
              add:
              - CAP_CHOWN
          volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
        - name: logs
          emptyDir: {}