kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: erpnext
    chart: erpnext-5.0.20
    heritage: Helm
    release: erpnext
  name: erpnext
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "8Gi"
  storageClassName: efs-sc