apiVersion: v1
kind: Service
metadata:
  name: erpnext-gunicorn
  labels:
    helm.sh/chart: erpnext-5.0.20
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/version: "v14.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: erpnext-gunicorn
    app.kubernetes.io/instance: erpnext-gunicorn