apiVersion: v1
kind: ServiceAccount
metadata:
  name: erpnext
  labels:

    helm.sh/chart: erpnext-5.0.20
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext
    app.kubernetes.io/version: "v14.2.0"
    app.kubernetes.io/managed-by: Helm