apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: client-api-luuna
  namespace: client-api
  labels:
    app: client-api-luuna
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-api-luuna
  minReplicas: 15
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
