apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: client-api-nooz
  namespace: client-api
  labels:
    app: client-api-nooz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-api-nooz
  minReplicas: 5
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
