namespace: zefin

#generators:
#  - secret-generator.yaml

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zefin-loan-gateway
      namespace: zefin
    spec:
      template:
        spec:
          containers:
          - name: zefin-loan-gateway
            image: luuna/zefin-loan-gateway:staging-a125e72432111882bffdd40b738e16c81cdf28be

  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: zefin-loan-gateway
      namespace: zefin
    data:
      FLASK_APP: "app:create_app()"
      FLASK_ENV: "staging"
      LOAN_APPLICATION_SERVICE_URL: "http://zefin-loan-origination-system"
      ZECORE_CLIENT_GRAPHQL_SERVER: "http://ms-client-graphql.client.svc.cluster.local/graphql"
