apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: erpnext-worker-l-autoscaler
  namespace: erpnext
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erpnext-worker-l
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70