apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: erpnext-autoscaler
  namespace: erpnext
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erpnext-erpnext
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: External
      external:
        metric:
          name: http_requests_erpnext
          selector: 
        target:
          type: Value
          value: 50000m 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10