apiVersion: v1
stringData:
    NEXT_PUBLIC_MATI_IDENTITY_CLIENT_ID: ENC[AES256_GCM,data:NUpneX9F499t3U70m4uhwkZmoORnHmmH,iv:o/2CsI8c2puS+nDFWD1SYm1P1ru7LaM6mUv8xU9oOno=,tag:pgsd4TgBC1vUmLsrNzCqVg==,type:str]
    NEXT_PUBLIC_MATI_IDENTITY_FLOW_ID: ENC[AES256_GCM,data:QmEHs0BKruFvJ6zt45xRG2QMLKcBUhrm,iv:p8+EoNI9lKMd5TYhc8A4lFiSqlvKUAHVoRl/zfENKm4=,tag:km0khmTYI/RuZbSd3ySFkw==,type:str]
kind: Secret
metadata:
    name: zefin-user-data-intake-system
    namespace: zefin
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:027984065276:key/6d825f6d-2b0c-47b7-aa8a-01ee6a47a8a4
          created_at: "2021-10-28T22:45:04Z"
          enc: AQICAHiHxEYmuD08pRo6Ex/h5uv3aLL8ZXoWr7ipNRSidKfQ4wF+C8FqgSZEHp4ex4LNhxa9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf6m8xsYZkKGV7kQ1AgEQgDs7ECThWoMp0HVEr+kgRmaYtB1TBxh8O+Z5k1y0qer2e5MItLIQNWgGaz0ocCv4ryjCQAKWCdmDZymRbA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T19:27:40Z"
    mac: ENC[AES256_GCM,data:dN95+/sKb60LOY5wX0a3jBMGb7AKGY10O6lT38ZWDe70N2wK+LM/bY1XvBEatnAHpMNTQ9wtSB0Oli0X2+xvV8VC81Bs5sARMMNcdcHuam8kPQg1zeNoCg2j6UJx9qJQe1bT8q9uuRqafS+T3DZxYCATvFBIfIxw0ZIzbNkCChY=,iv:R6Fx0rkb00rHQ0LDPu8UPSIAdj8xhu9jCNiiZq4eL3w=,tag:N2th0Mz7AZoge07+QcjHLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
